// Design Style Finder Pro - Data Module

const styles = [
  // ===== MINIMAL (9種) =====
  { id: 'swiss', name: 'Swiss Minimal', nameJp: 'スイスミニマル', tone: 'minimal', desc: 'グリッドを重視した合理的なデザイン。赤のアクセントが特徴。', tags: ['グリッド', '赤アクセント', 'サンセリフ'], colors: [{ hex: '#FFFFFF', name: 'ベース' }, { hex: '#000000', name: '文字' }, { hex: '#E53935', name: 'アクセント' }], fonts: [{ label: '見出し', name: 'Helvetica / Outfit' }, { label: '本文', name: 'Noto Sans JP' }], features: ['厳格なグリッド', '余白の美学', '赤の差し色', '大きな数字'], previewClass: 'preview-swiss', yaml: `# Swiss Minimal Style\n全体デザイン設定:\n  トーン: "合理的、機能美、スイスデザイン"\n  配色パレット:\n    ベース: "#FFFFFF"\n    文字色: "#000000"\n    アクセント: "#E53935 (赤)"\n  タイポグラフィ:\n    見出し: "Helvetica系、極太"\n  共通レイアウト:\n    グリッド: "12カラム厳格グリッド"\n    装飾: "赤のアクセントライン"` },
  { id: 'japanese', name: 'Japanese Minimal', nameJp: '和モダン', tone: 'minimal', desc: '日本の美意識を現代的に解釈。余白と縦のラインが特徴。', tags: ['和風', '縦線', '明朝体'], colors: [{ hex: '#FAFAF8', name: '生成り' }, { hex: '#1A1A1A', name: '墨色' }, { hex: '#8B7355', name: '茶' }], fonts: [{ label: '見出し', name: 'Noto Serif JP' }, { label: '本文', name: 'Noto Sans JP Light' }], features: ['縦のライン', '余白重視', '明朝体', '中央配置'], previewClass: 'preview-japanese', yaml: `# Japanese Minimal Style\n全体デザイン設定:\n  トーン: "静謐、余白の美、和モダン"\n  配色パレット:\n    ベース: "#FAFAF8 (生成り)"\n    文字色: "#1A1A1A (墨色)"\n  タイポグラフィ:\n    見出し: "明朝体、字間広め"\n  共通レイアウト:\n    余白: "たっぷり"\n    ライン: "細い縦線"` },
  { id: 'nordic', name: 'Nordic Minimal', nameJp: '北欧ミニマル', tone: 'minimal', desc: '温かみのあるニュートラルカラー。丸みと柔らかさが特徴。', tags: ['北欧', '丸み', 'ニュートラル'], colors: [{ hex: '#F5F3EF', name: 'ベース' }, { hex: '#2D3436', name: '文字' }, { hex: '#74B9FF', name: 'アクセント' }], fonts: [{ label: '見出し', name: 'DM Sans Bold' }, { label: '本文', name: 'DM Sans' }], features: ['丸い角', 'ソフトシャドウ', 'カードUI', '温かみ'], previewClass: 'preview-nordic', yaml: `# Nordic Minimal Style\n全体デザイン設定:\n  トーン: "温かみ、北欧デザイン"\n  配色パレット:\n    ベース: "#F5F3EF"\n    アクセント: "#74B9FF"\n  タイポグラフィ:\n    見出し: "丸みのあるサンセリフ"\n  共通レイアウト:\n    角丸: "16px"\n    シャドウ: "ソフト"` },
  { id: 'mono', name: 'Pure Monochrome', nameJp: 'ピュアモノクロ', tone: 'minimal', desc: '白と黒のみ。フォントの強弱と構成力で魅せる。', tags: ['モノクロ', 'タイポ', 'コントラスト'], colors: [{ hex: '#FFFFFF', name: 'ベース' }, { hex: '#000000', name: '文字' }, { hex: '#666666', name: 'サブ' }], fonts: [{ label: '見出し', name: 'Outfit Bold' }, { label: '本文', name: 'Noto Sans JP' }], features: ['白黒のみ', 'サイズ対比', '黒ブロック'], previewClass: 'preview-mono', yaml: `# Pure Monochrome Style\n全体デザイン設定:\n  トーン: "ストイック、モノクローム"\n  配色パレット:\n    ベース: "#FFFFFF"\n    文字色: "#000000"\n  タイポグラフィ:\n    見出し: "太いサンセリフ、大文字"\n  共通レイアウト:\n    対比: "フォントサイズの極端な差"` },
  { id: 'editorial', name: 'Editorial', nameJp: 'エディトリアル', tone: 'minimal', desc: '雑誌のような洗練されたレイアウト。セリフ体の美しさ。', tags: ['雑誌風', 'セリフ', '非対称'], colors: [{ hex: '#FFFFFF', name: 'ベース' }, { hex: '#1A1A1A', name: '文字' }, { hex: '#999999', name: 'サブ' }], fonts: [{ label: '見出し', name: 'Playfair Display' }, { label: '本文', name: 'Noto Sans JP Light' }], features: ['セリフ見出し', 'アイブロウ', '細いライン'], previewClass: 'preview-editorial', yaml: `# Editorial Style\n全体デザイン設定:\n  トーン: "洗練、雑誌的"\n  配色パレット:\n    ベース: "#FFFFFF"\n    文字色: "#1A1A1A"\n  タイポグラフィ:\n    見出し: "Playfair Display"\n    アイブロウ: "極小、大文字"` },
  { id: 'architectural', name: 'Architectural', nameJp: 'アーキテクチュラル', tone: 'minimal', desc: '建築図面のような精密さ。グリッドと細い線。', tags: ['建築', 'グリッド', '精密'], colors: [{ hex: '#F5F5F5', name: 'ベース' }, { hex: '#1A1A1A', name: '文字' }, { hex: '#CCCCCC', name: 'グリッド' }], fonts: [{ label: '見出し', name: 'Outfit SemiBold' }, { label: '本文', name: 'Noto Sans JP Light' }], features: ['グリッド背景', '大きな数字', '大文字'], previewClass: 'preview-architectural', yaml: `# Architectural Style\n全体デザイン設定:\n  トーン: "精密、建築的"\n  配色パレット:\n    ベース: "#F5F5F5"\n    グリッド: "#CCCCCC"\n  タイポグラフィ:\n    見出し: "大文字、letter-spacing広め"\n  共通レイアウト:\n    グリッド: "40px方眼"` },
  { id: 'bauhaus', name: 'Bauhaus', nameJp: 'バウハウス', tone: 'minimal', desc: '原色と幾何学形状。モダンデザインの原点。', tags: ['原色', '幾何学', 'モダン'], colors: [{ hex: '#F5F5F0', name: 'ベース' }, { hex: '#1A1A1A', name: '文字' }, { hex: '#E53935', name: '赤' }, { hex: '#1565C0', name: '青' }], fonts: [{ label: '見出し', name: 'Outfit Extra Bold' }], features: ['原色使い', '円と四角', '大胆な構成'], previewClass: 'preview-bauhaus', yaml: `# Bauhaus Style\n全体デザイン設定:\n  トーン: "モダン、バウハウス"\n  配色パレット:\n    原色: "赤#E53935、青#1565C0、黄#FDD835"\n  タイポグラフィ:\n    見出し: "極太、大文字"\n  共通レイアウト:\n    図形: "円、四角、三角の組み合わせ"` },
  { id: 'scandi', name: 'Scandinavian Light', nameJp: 'スカンジナビアン', tone: 'minimal', desc: '明るく開放的。自然光を感じさせる白基調。', tags: ['白基調', '軽やか', '自然'], colors: [{ hex: '#FFFFFF', name: 'ベース' }, { hex: '#333333', name: '文字' }, { hex: '#E8E8E8', name: 'サブ' }], fonts: [{ label: '見出し', name: 'DM Sans Bold' }], features: ['白基調', '自然光感', 'シンプル'], previewClass: 'preview-scandi', yaml: `# Scandinavian Light Style\n全体デザイン設定:\n  トーン: "明るい、開放的"\n  配色パレット:\n    ベース: "#FFFFFF"\n    文字色: "#333333"\n  共通レイアウト:\n    余白: "たっぷり"\n    装飾: "最小限"` },
  { id: 'zen', name: 'Zen', nameJp: '禅', tone: 'minimal', desc: '究極の静けさ。円と直線、無駄のない構成。', tags: ['禅', '円', '静寂'], colors: [{ hex: '#E8E4DC', name: 'ベース' }, { hex: '#3D3D3D', name: '文字' }, { hex: '#D4CFC4', name: 'サブ' }], fonts: [{ label: '見出し', name: 'Noto Serif JP' }], features: ['円形モチーフ', '静けさ', '砂色'], previewClass: 'preview-zen', yaml: `# Zen Style\n全体デザイン設定:\n  トーン: "静寂、禅"\n  配色パレット:\n    ベース: "#E8E4DC (砂)"\n    文字色: "#3D3D3D"\n  タイポグラフィ:\n    見出し: "明朝体"\n  共通レイアウト:\n    モチーフ: "円、直線のみ"` },

  // ===== TECH (8種) =====
  { id: 'tech-dark', name: 'Tech Dark', nameJp: 'テックダーク', tone: 'tech', desc: 'ダークモードベース。グリッドとグローエフェクトが特徴。', tags: ['ダーク', 'グリッド', 'グロー'], colors: [{ hex: '#0F0F1A', name: 'ベース' }, { hex: '#FFFFFF', name: '文字' }, { hex: '#4285F4', name: 'ブルー' }, { hex: '#9C5CFF', name: 'パープル' }], fonts: [{ label: '見出し', name: 'Space Grotesk' }, { label: 'コード', name: 'JetBrains Mono' }], features: ['グリッド背景', 'グロー効果', 'バッジUI'], previewClass: 'preview-tech-dark', yaml: `# Tech Dark Style\n全体デザイン設定:\n  トーン: "先進的、ダークモード"\n  配色パレット:\n    ベース: "#0F0F1A"\n    アクセント: "#4285F4 → #9C5CFF"\n  タイポグラフィ:\n    見出し: "Space Grotesk"\n  共通レイアウト:\n    背景: "グリッドパターン"` },
  { id: 'neon', name: 'Neon Glow', nameJp: 'ネオングロー', tone: 'tech', desc: '鮮やかなネオンカラー。ダーク背景に映える光の演出。', tags: ['ネオン', '発光', 'サイバー'], colors: [{ hex: '#0A0A0A', name: 'ベース' }, { hex: '#FFFFFF', name: '文字' }, { hex: '#00FF88', name: 'ネオン' }], fonts: [{ label: '見出し', name: 'Outfit Bold' }, { label: 'コード', name: 'JetBrains Mono' }], features: ['発光効果', 'ネオンカラー', 'text-shadow'], previewClass: 'preview-neon', yaml: `# Neon Glow Style\n全体デザイン設定:\n  トーン: "サイバー、ネオン"\n  配色パレット:\n    ベース: "#0A0A0A"\n    ネオン: "#00FF88"\n  共通レイアウト:\n    効果: "text-shadow、グロー"` },
  { id: 'cyber', name: 'Cyberpunk', nameJp: 'サイバーパンク', tone: 'tech', desc: 'マゼンタとシアンのグラデーション。SF的な世界観。', tags: ['SF', 'グラデ', 'パンク'], colors: [{ hex: '#1A0033', name: 'ベース' }, { hex: '#FF00FF', name: 'マゼンタ' }, { hex: '#00FFFF', name: 'シアン' }], fonts: [{ label: '見出し', name: 'Outfit Extra Bold' }], features: ['スキャンライン', 'グラデ文字', 'SF感'], previewClass: 'preview-cyber', yaml: `# Cyberpunk Style\n全体デザイン設定:\n  トーン: "SF、サイバーパンク"\n  配色パレット:\n    グラデーション: "#FF00FF → #00FFFF"\n  共通レイアウト:\n    効果: "スキャンライン"` },
  { id: 'terminal', name: 'Terminal', nameJp: 'ターミナル', tone: 'tech', desc: 'コマンドライン風。開発者向けの技術的な印象。', tags: ['CLI', 'モノスペース', '開発者'], colors: [{ hex: '#0D1117', name: 'ベース' }, { hex: '#C9D1D9', name: '文字' }, { hex: '#7EE787', name: 'グリーン' }], fonts: [{ label: '全体', name: 'JetBrains Mono' }], features: ['モノスペース', 'プロンプト風'], previewClass: 'preview-terminal', yaml: `# Terminal Style\n全体デザイン設定:\n  トーン: "開発者向け、CLI風"\n  配色パレット:\n    ベース: "#0D1117"\n    プロンプト: "#7EE787"\n  タイポグラフィ:\n    全体: "JetBrains Mono"` },
  { id: 'matrix', name: 'Matrix', nameJp: 'マトリックス', tone: 'tech', desc: '緑の文字が流れ落ちるイメージ。映画的な世界観。', tags: ['緑', '映画的', 'コード'], colors: [{ hex: '#0A0A0A', name: 'ベース' }, { hex: '#00FF41', name: 'グリーン' }], fonts: [{ label: '全体', name: 'JetBrains Mono' }], features: ['緑単色', 'コード雨', '映画的'], previewClass: 'preview-matrix', yaml: `# Matrix Style\n全体デザイン設定:\n  トーン: "映画的、ハッカー風"\n  配色パレット:\n    ベース: "#0A0A0A"\n    文字色: "#00FF41"` },
  { id: 'holographic', name: 'Holographic', nameJp: 'ホログラフィック', tone: 'tech', desc: '虹色に輝くホログラム効果。未来的で幻想的。', tags: ['虹色', '未来', '幻想的'], colors: [{ hex: '#1A1A2E', name: 'ベース' }, { hex: '#A8EDEA', name: 'ミント' }, { hex: '#FED6E3', name: 'ピンク' }], fonts: [{ label: '見出し', name: 'Space Grotesk' }], features: ['虹色グラデ', 'シマー効果'], previewClass: 'preview-holographic', yaml: `# Holographic Style\n全体デザイン設定:\n  トーン: "未来的、ホログラム"\n  配色パレット:\n    グラデーション: "虹色 (ミント→ピンク→ミント)"` },
  { id: 'ai', name: 'AI Neural', nameJp: 'AIニューラル', tone: 'tech', desc: 'ニューラルネットワークを連想させる。ノードと接続線。', tags: ['AI', 'ノード', 'ネットワーク'], colors: [{ hex: '#0F0F1A', name: 'ベース' }, { hex: '#FFFFFF', name: '文字' }, { hex: '#4285F4', name: 'ノード' }], fonts: [{ label: '見出し', name: 'Space Grotesk' }], features: ['ノード図', '接続線', 'AI感'], previewClass: 'preview-ai', yaml: `# AI Neural Style\n全体デザイン設定:\n  トーン: "AI、ニューラルネットワーク"\n  配色パレット:\n    ベース: "#0F0F1A"\n    ノード: "#4285F4"\n  共通レイアウト:\n    図形: "ノードを線で繋ぐ"` },
  { id: 'darkpro', name: 'Dark Mode Pro', nameJp: 'ダークモードPro', tone: 'tech', desc: '洗練されたダークUI。プロフェッショナル向け。', tags: ['ダーク', 'プロ', '洗練'], colors: [{ hex: '#18181B', name: 'ベース' }, { hex: '#FAFAFA', name: '文字' }, { hex: '#4285F4', name: 'アクセント' }], fonts: [{ label: '見出し', name: 'DM Sans Bold' }], features: ['ダークUI', 'アクセントライン', '洗練'], previewClass: 'preview-darkpro', yaml: `# Dark Mode Pro Style\n全体デザイン設定:\n  トーン: "洗練、プロフェッショナル"\n  配色パレット:\n    ベース: "#18181B"\n    文字色: "#FAFAFA"\n    アクセント: "グラデーションライン"` },

  // ===== CASUAL (8種) =====
  { id: 'playful', name: 'Playful', nameJp: 'プレイフル', tone: 'casual', desc: 'ポップなグラデーションと遊び心のある図形。', tags: ['ポップ', 'グラデ', '絵文字'], colors: [{ hex: '#667EEA', name: 'パープル' }, { hex: '#764BA2', name: 'ディープ' }], fonts: [{ label: '見出し', name: 'Poppins Bold' }], features: ['グラデ背景', '幾何学図形', '絵文字'], previewClass: 'preview-playful', yaml: `# Playful Style\n全体デザイン設定:\n  トーン: "ポップ、遊び心"\n  配色パレット:\n    グラデーション: "#667EEA → #764BA2"\n  共通レイアウト:\n    装飾: "半透明図形"\n    アイコン: "絵文字"` },
  { id: 'soft', name: 'Soft Pastel', nameJp: 'ソフトパステル', tone: 'casual', desc: '柔らかいグラデーションとグラスモーフィズム。', tags: ['パステル', 'ガラス', '柔らかい'], colors: [{ hex: '#FFECD2', name: 'ピーチ' }, { hex: '#FCB69F', name: 'コーラル' }], fonts: [{ label: '見出し', name: 'DM Sans Bold' }], features: ['グラスモーフィズム', 'パステル', '大きな角丸'], previewClass: 'preview-soft', yaml: `# Soft Pastel Style\n全体デザイン設定:\n  トーン: "柔らかい、パステル"\n  配色パレット:\n    グラデーション: "#FFECD2 → #FCB69F"\n  共通レイアウト:\n    カード: "グラスモーフィズム"` },
  { id: 'fresh', name: 'Fresh', nameJp: 'フレッシュ', tone: 'casual', desc: 'ミントグリーンの爽やかさ。健康的でクリーンな印象。', tags: ['ミント', '爽やか', 'クリーン'], colors: [{ hex: '#FFFFFF', name: 'ベース' }, { hex: '#84FAB0', name: 'ミント' }, { hex: '#8FD3F4', name: 'スカイ' }], fonts: [{ label: '見出し', name: 'Poppins SemiBold' }], features: ['ブロブ形状', 'グリーン系', 'タグUI'], previewClass: 'preview-fresh', yaml: `# Fresh Style\n全体デザイン設定:\n  トーン: "爽やか、健康的"\n  配色パレット:\n    アクセント: "#84FAB0 → #8FD3F4"\n  共通レイアウト:\n    装飾: "有機的ブロブ"` },
  { id: 'rounded', name: 'Rounded Card', nameJp: 'ラウンドカード', tone: 'casual', desc: '大きな角丸とソフトシャドウ。アプリUI風。', tags: ['カード', '角丸', 'アプリ風'], colors: [{ hex: '#F8F9FA', name: 'ベース' }, { hex: '#FFD93D', name: 'イエロー' }, { hex: '#FF6B6B', name: 'コーラル' }], fonts: [{ label: '見出し', name: 'DM Sans Bold' }], features: ['大きな角丸', 'ソフトシャドウ', 'アバター'], previewClass: 'preview-rounded', yaml: `# Rounded Card Style\n全体デザイン設定:\n  トーン: "フレンドリー、アプリ風"\n  共通レイアウト:\n    角丸: "24px"\n    シャドウ: "ソフト"` },
  { id: 'kawaii', name: 'Kawaii', nameJp: 'カワイイ', tone: 'casual', desc: 'ピンク×パープルのかわいい配色。絵文字多用。', tags: ['ピンク', 'かわいい', '絵文字'], colors: [{ hex: '#FFC3D8', name: 'ピンク' }, { hex: '#D4A5FF', name: 'ラベンダー' }], fonts: [{ label: '見出し', name: 'DM Sans Bold' }], features: ['ピンク系', '絵文字', '丸み'], previewClass: 'preview-kawaii', yaml: `# Kawaii Style\n全体デザイン設定:\n  トーン: "かわいい、ポップ"\n  配色パレット:\n    グラデーション: "#FFC3D8 → #D4A5FF"\n  共通レイアウト:\n    アイコン: "絵文字多用"` },
  { id: 'organic', name: 'Organic', nameJp: 'オーガニック', tone: 'casual', desc: '自然を感じる有機的な形と色。エコフレンドリー。', tags: ['自然', 'グリーン', '有機的'], colors: [{ hex: '#F9F7F4', name: 'ベース' }, { hex: '#C5E1A5', name: 'グリーン' }], fonts: [{ label: '見出し', name: 'DM Sans Bold' }], features: ['有機的形状', 'グリーン系', '自然感'], previewClass: 'preview-organic', yaml: `# Organic Style\n全体デザイン設定:\n  トーン: "自然、エコ"\n  配色パレット:\n    アクセント: "#C5E1A5 (グリーン)"\n  共通レイアウト:\n    図形: "有機的ブロブ"` },
  { id: 'friendly', name: 'Friendly App', nameJp: 'フレンドリーアプリ', tone: 'casual', desc: 'アプリUIに最適。青系の信頼感と親しみやすさ。', tags: ['アプリ', '青', '親しみ'], colors: [{ hex: '#4361EE', name: 'ブルー' }, { hex: '#FFFFFF', name: '文字' }], fonts: [{ label: '見出し', name: 'Poppins SemiBold' }], features: ['青基調', 'カードUI', 'アイコン'], previewClass: 'preview-friendly', yaml: `# Friendly App Style\n全体デザイン設定:\n  トーン: "親しみやすい、アプリ"\n  配色パレット:\n    プライマリ: "#4361EE"\n  共通レイアウト:\n    カード: "半透明カード"` },
  { id: 'memphis', name: 'Memphis', nameJp: 'メンフィス', tone: 'casual', desc: '80年代ポップ。ドット、三角、ジグザグの装飾。', tags: ['80s', 'ポップ', 'パターン'], colors: [{ hex: '#F5F5F5', name: 'ベース' }, { hex: '#FF6B6B', name: '赤' }, { hex: '#FFD93D', name: '黄' }, { hex: '#4ECDC4', name: '水色' }], fonts: [{ label: '見出し', name: 'Outfit Extra Bold' }], features: ['ドット', '三角', 'ジグザグ', '80sポップ'], previewClass: 'preview-memphis', yaml: `# Memphis Style\n全体デザイン設定:\n  トーン: "80s、ポップ"\n  配色パレット:\n    カラフル: "赤、黄、水色"\n  共通レイアウト:\n    装飾: "ドット、三角、線"` },

  // ===== PREMIUM (8種) =====
  { id: 'luxury', name: 'Luxury Gold', nameJp: 'ラグジュアリー', tone: 'premium', desc: '黒背景にゴールドのアクセント。最上級の高級感。', tags: ['ゴールド', 'ダーク', '高級'], colors: [{ hex: '#0A0A0A', name: 'ベース' }, { hex: '#D4AF37', name: 'ゴールド' }], fonts: [{ label: '見出し', name: 'Playfair Display' }], features: ['ゴールドライン', 'セリフ体', '中央配置'], previewClass: 'preview-luxury', yaml: `# Luxury Gold Style\n全体デザイン設定:\n  トーン: "高級、ラグジュアリー"\n  配色パレット:\n    ベース: "#0A0A0A"\n    アクセント: "#D4AF37 (ゴールド)"` },
  { id: 'brutalist', name: 'Brutalist', nameJp: 'ブルータリスト', tone: 'premium', desc: '力強いコントラスト。太い線と大胆なタイポグラフィ。', tags: ['モノクロ', '太字', 'ボーダー'], colors: [{ hex: '#000000', name: 'ベース' }, { hex: '#FFFFFF', name: '文字' }], fonts: [{ label: '見出し', name: 'Outfit Extra Bold' }, { label: '本文', name: 'JetBrains Mono' }], features: ['太いボーダー', '大文字', 'モノスペース'], previewClass: 'preview-brutalist', yaml: `# Brutalist Style\n全体デザイン設定:\n  トーン: "力強い、ブルータリズム"\n  配色パレット:\n    ベース: "#000000"\n    文字色: "#FFFFFF"\n  共通レイアウト:\n    ボーダー: "4px以上"` },
  { id: 'artdeco', name: 'Art Deco', nameJp: 'アールデコ', tone: 'premium', desc: '1920年代の華やかさ。金の装飾と幾何学模様。', tags: ['1920s', 'ゴールド', '幾何学'], colors: [{ hex: '#1A1A2E', name: 'ベース' }, { hex: '#D4AF37', name: 'ゴールド' }], fonts: [{ label: '見出し', name: 'Playfair Display' }], features: ['ゴールド枠', '幾何学模様', 'コーナー装飾'], previewClass: 'preview-artdeco', yaml: `# Art Deco Style\n全体デザイン設定:\n  トーン: "1920s、華やか"\n  配色パレット:\n    ベース: "#1A1A2E"\n    装飾: "#D4AF37"\n  共通レイアウト:\n    枠: "ゴールドのフレーム"` },
  { id: 'marble', name: 'Marble', nameJp: 'マーブル', tone: 'premium', desc: '大理石のような質感。上品で落ち着いた印象。', tags: ['大理石', '上品', 'テクスチャ'], colors: [{ hex: '#F5F5F5', name: 'マーブル' }, { hex: '#1A1A1A', name: '文字' }], fonts: [{ label: '見出し', name: 'Playfair Display' }], features: ['大理石テクスチャ', 'セリフ体', '中央配置'], previewClass: 'preview-marble', yaml: `# Marble Style\n全体デザイン設定:\n  トーン: "上品、大理石"\n  配色パレット:\n    背景: "マーブルグラデーション"\n  タイポグラフィ:\n    見出し: "Playfair Display"` },
  { id: 'noir', name: 'Film Noir', nameJp: 'フィルムノワール', tone: 'premium', desc: '映画的な陰影。ドラマチックで神秘的な雰囲気。', tags: ['映画的', 'モノクロ', '陰影'], colors: [{ hex: '#1A1A1A', name: 'ベース' }, { hex: '#FFFFFF', name: '文字' }], fonts: [{ label: '見出し', name: 'Playfair Display' }], features: ['ヴィネット', 'イタリック', '陰影'], previewClass: 'preview-noir', yaml: `# Film Noir Style\n全体デザイン設定:\n  トーン: "映画的、ドラマチック"\n  配色パレット:\n    ベース: "グラデーション黒"\n  共通レイアウト:\n    効果: "ヴィネット"` },
  { id: 'serif', name: 'Classic Serif', nameJp: 'クラシックセリフ', tone: 'premium', desc: '伝統的な書体の美しさ。読みやすく上品。', tags: ['セリフ', '伝統', '読みやすい'], colors: [{ hex: '#FFFEF9', name: 'ベース' }, { hex: '#1A1A1A', name: '文字' }], fonts: [{ label: '全体', name: 'Crimson Pro' }], features: ['セリフ体のみ', '伝統的', 'イタリック'], previewClass: 'preview-serif', yaml: `# Classic Serif Style\n全体デザイン設定:\n  トーン: "伝統的、クラシック"\n  タイポグラフィ:\n    全体: "Crimson Pro等のセリフ体"` },
  { id: 'museum', name: 'Museum', nameJp: 'ミュージアム', tone: 'premium', desc: '美術館のキャプションのような。控えめで知的。', tags: ['美術館', '知的', 'キャプション'], colors: [{ hex: '#FAFAFA', name: 'ベース' }, { hex: '#1A1A1A', name: '文字' }, { hex: '#999999', name: 'ラベル' }], fonts: [{ label: '見出し', name: 'Outfit SemiBold' }], features: ['ラベル風', '控えめ', 'メタ情報'], previewClass: 'preview-museum', yaml: `# Museum Style\n全体デザイン設定:\n  トーン: "知的、美術館風"\n  共通レイアウト:\n    ラベル: "極小、大文字"\n    情報: "作品名、年代、素材"` },
  { id: 'fashion', name: 'Fashion', nameJp: 'ファッション', tone: 'premium', desc: 'ファッション誌のような。letter-spacing広めの大文字。', tags: ['ファッション', '大文字', 'スタイリッシュ'], colors: [{ hex: '#000000', name: 'ベース' }, { hex: '#FFFFFF', name: '文字' }], fonts: [{ label: '見出し', name: 'Outfit Light' }], features: ['大文字', 'letter-spacing広', '細い線'], previewClass: 'preview-fashion', yaml: `# Fashion Style\n全体デザイン設定:\n  トーン: "ファッション、スタイリッシュ"\n  タイポグラフィ:\n    見出し: "細字、大文字、letter-spacing: 8px"` },

  // ===== CREATIVE (8種) =====
  { id: 'geometric', name: 'Geometric', nameJp: 'ジオメトリック', tone: 'creative', desc: '幾何学的な図形を装飾に。構造的で知的な印象。', tags: ['幾何学', '図形', 'レイヤー'], colors: [{ hex: '#1A1A2E', name: 'ベース' }, { hex: '#E94560', name: '赤' }, { hex: '#0F3460', name: '青' }], fonts: [{ label: '見出し', name: 'Outfit Bold' }], features: ['円と四角', 'アウトライン', 'レイヤー'], previewClass: 'preview-geometric', yaml: `# Geometric Style\n全体デザイン設定:\n  トーン: "構造的、幾何学"\n  配色パレット:\n    アクセント: "#E94560"\n  共通レイアウト:\n    図形: "円、四角をアウトラインで"` },
  { id: 'retro', name: 'Retro', nameJp: 'レトロ', tone: 'creative', desc: 'ヴィンテージ感のある配色。懐かしさと新しさの融合。', tags: ['ヴィンテージ', 'アンバー', 'バッジ'], colors: [{ hex: '#FEF3C7', name: 'クリーム' }, { hex: '#78350F', name: 'ブラウン' }], fonts: [{ label: '見出し', name: 'Outfit Extra Bold' }], features: ['クリーム背景', 'バッジ装飾', 'レトロ感'], previewClass: 'preview-retro', yaml: `# Retro Style\n全体デザイン設定:\n  トーン: "ヴィンテージ、レトロ"\n  配色パレット:\n    ベース: "#FEF3C7"\n    文字色: "#78350F"` },
  { id: 'gradient', name: 'Bold Gradient', nameJp: 'ボールドグラデ', tone: 'creative', desc: '大胆なマルチカラーグラデーション。インパクト重視。', tags: ['グラデ', 'マルチカラー', '大胆'], colors: [{ hex: '#F093FB', name: 'ピンク' }, { hex: '#F5576C', name: 'レッド' }, { hex: '#4FACFE', name: 'ブルー' }], fonts: [{ label: '見出し', name: 'Poppins Bold' }], features: ['3色グラデ', 'text-shadow', 'インパクト'], previewClass: 'preview-gradient', yaml: `# Bold Gradient Style\n全体デザイン設定:\n  トーン: "大胆、カラフル"\n  配色パレット:\n    グラデーション: "#F093FB → #F5576C → #4FACFE"` },
  { id: 'duotone', name: 'Duotone', nameJp: 'デュオトーン', tone: 'creative', desc: '2色で構成するビジュアル。写真にも適用可能。', tags: ['2色', 'フィルター', 'モダン'], colors: [{ hex: '#1A1A2E', name: 'ベース' }, { hex: '#4FACFE', name: 'ブルー' }, { hex: '#00F2FE', name: 'シアン' }], fonts: [{ label: '見出し', name: 'Space Grotesk' }], features: ['デュオトーン画像', 'グラデ装飾'], previewClass: 'preview-duotone', yaml: `# Duotone Style\n全体デザイン設定:\n  トーン: "アーティスティック"\n  配色パレット:\n    デュオトーン: "#4FACFE → #00F2FE"\n  共通レイアウト:\n    画像: "デュオトーンフィルター"` },
  { id: 'popart', name: 'Pop Art', nameJp: 'ポップアート', tone: 'creative', desc: 'ウォーホル風。ドットパターンと原色。', tags: ['ポップ', 'ドット', '原色'], colors: [{ hex: '#FFEB3B', name: 'イエロー' }, { hex: '#FF5722', name: 'オレンジ' }], fonts: [{ label: '見出し', name: 'Outfit Extra Bold' }], features: ['ドットパターン', '原色', '大胆'], previewClass: 'preview-popart', yaml: `# Pop Art Style\n全体デザイン設定:\n  トーン: "ポップアート、大胆"\n  配色パレット:\n    原色: "黄、オレンジ、赤"\n  共通レイアウト:\n    パターン: "ドット"` },
  { id: 'collage', name: 'Collage', nameJp: 'コラージュ', tone: 'creative', desc: '重なり合うレイヤー。アナログ感のあるデジタル表現。', tags: ['レイヤー', 'アナログ', '重なり'], colors: [{ hex: '#F5F5F5', name: 'ベース' }, { hex: '#E0E0E0', name: 'レイヤー1' }, { hex: '#4285F4', name: 'レイヤー2' }], fonts: [{ label: '見出し', name: 'Outfit Bold' }], features: ['レイヤー重ね', '回転', 'アナログ感'], previewClass: 'preview-collage', yaml: `# Collage Style\n全体デザイン設定:\n  トーン: "コラージュ、アナログ"\n  共通レイアウト:\n    レイヤー: "回転させて重ねる"` },
  { id: 'grunge', name: 'Grunge', nameJp: 'グランジ', tone: 'creative', desc: 'ノイズとテクスチャ。荒々しく力強い。', tags: ['ノイズ', 'テクスチャ', '荒々しい'], colors: [{ hex: '#2A2A2A', name: 'ベース' }, { hex: '#E0E0E0', name: '文字' }], fonts: [{ label: '見出し', name: 'Outfit Extra Bold' }], features: ['ノイズ', 'テクスチャ', '大文字'], previewClass: 'preview-grunge', yaml: `# Grunge Style\n全体デザイン設定:\n  トーン: "グランジ、荒々しい"\n  共通レイアウト:\n    効果: "ノイズテクスチャ"` },
  { id: 'experimental', name: 'Experimental', nameJp: 'エクスペリメンタル', tone: 'creative', desc: 'グリッチ効果やズレ。実験的で前衛的。', tags: ['グリッチ', '前衛', 'ズレ'], colors: [{ hex: '#0A0A0A', name: 'ベース' }, { hex: '#FFFFFF', name: '文字' }, { hex: '#FF0000', name: 'グリッチ' }], fonts: [{ label: '見出し', name: 'Outfit Extra Bold' }], features: ['グリッチ', 'ズレ', '実験的'], previewClass: 'preview-experimental', yaml: `# Experimental Style\n全体デザイン設定:\n  トーン: "前衛的、実験的"\n  共通レイアウト:\n    効果: "グリッチ、位置ズレ"` },

  // ===== CORPORATE (6種) =====
  { id: 'corporate', name: 'Corporate Blue', nameJp: 'コーポレートブルー', tone: 'corporate', desc: '信頼感のあるブルー基調。ビジネスシーンに最適。', tags: ['ブルー', 'ビジネス', '信頼'], colors: [{ hex: '#FFFFFF', name: 'ベース' }, { hex: '#3B82F6', name: 'ブルー' }, { hex: '#1D4ED8', name: 'ディープ' }], fonts: [{ label: '見出し', name: 'DM Sans Bold' }], features: ['ブルーロゴ', 'クリーン', '整然'], previewClass: 'preview-corporate', yaml: `# Corporate Blue Style\n全体デザイン設定:\n  トーン: "信頼、プロフェッショナル"\n  配色パレット:\n    プライマリ: "#3B82F6"` },
  { id: 'data', name: 'Data Driven', nameJp: 'データドリブン', tone: 'corporate', desc: 'データビジュアライゼーション向け。グラフと数字を美しく。', tags: ['データ', 'グラフ', '分析'], colors: [{ hex: '#F8FAFC', name: 'ベース' }, { hex: '#3B82F6', name: 'プライマリ' }, { hex: '#60A5FA', name: 'セカンダリ' }], fonts: [{ label: '数字', name: 'Outfit' }], features: ['バーチャート', 'グラデバー', '数字強調'], previewClass: 'preview-data', yaml: `# Data Driven Style\n全体デザイン設定:\n  トーン: "分析的、データ重視"\n  共通レイアウト:\n    グラフ: "グラデーションバー"` },
  { id: 'consulting', name: 'Consulting', nameJp: 'コンサルティング', tone: 'corporate', desc: '戦略コンサル風。ダークブルーの知的な印象。', tags: ['コンサル', 'ダークブルー', '知的'], colors: [{ hex: '#1E3A5F', name: 'ベース' }, { hex: '#FFFFFF', name: '文字' }, { hex: '#60A5FA', name: 'アクセント' }], fonts: [{ label: '見出し', name: 'DM Sans Bold' }], features: ['ダークブルー', 'アクセントライン', '知的'], previewClass: 'preview-consulting', yaml: `# Consulting Style\n全体デザイン設定:\n  トーン: "知的、戦略的"\n  配色パレット:\n    ベース: "#1E3A5F"` },
  { id: 'finance', name: 'Finance', nameJp: 'ファイナンス', tone: 'corporate', desc: '金融・投資向け。数字を大きく強調。', tags: ['金融', '数字', 'ダーク'], colors: [{ hex: '#0F172A', name: 'ベース' }, { hex: '#10B981', name: 'グリーン' }], fonts: [{ label: '数字', name: 'Outfit Bold' }], features: ['大きな数字', 'グリーン', '増減表示'], previewClass: 'preview-finance', yaml: `# Finance Style\n全体デザイン設定:\n  トーン: "金融、投資"\n  配色パレット:\n    ベース: "#0F172A"\n    ポジティブ: "#10B981"` },
  { id: 'healthcare', name: 'Healthcare', nameJp: 'ヘルスケア', tone: 'corporate', desc: '医療・健康分野向け。グリーンの安心感。', tags: ['医療', 'グリーン', '安心'], colors: [{ hex: '#F0FDF4', name: 'ベース' }, { hex: '#166534', name: '文字' }, { hex: '#16A34A', name: 'アクセント' }], fonts: [{ label: '見出し', name: 'DM Sans Bold' }], features: ['グリーン基調', 'アイコン', '安心感'], previewClass: 'preview-healthcare', yaml: `# Healthcare Style\n全体デザイン設定:\n  トーン: "医療、安心"\n  配色パレット:\n    ベース: "#F0FDF4"\n    アクセント: "#16A34A"` },
  { id: 'legal', name: 'Legal', nameJp: 'リーガル', tone: 'corporate', desc: '法律・士業向け。重厚で信頼感のある印象。', tags: ['法律', '重厚', '信頼'], colors: [{ hex: '#1C1917', name: 'ベース' }, { hex: '#FAFAF9', name: '文字' }], fonts: [{ label: '見出し', name: 'Playfair Display' }], features: ['ダーク', 'セリフ体', '重厚'], previewClass: 'preview-legal', yaml: `# Legal Style\n全体デザイン設定:\n  トーン: "重厚、信頼"\n  配色パレット:\n    ベース: "#1C1917"\n  タイポグラフィ:\n    見出し: "Playfair Display"` }
];

const tones = [
  { id: 'all', emoji: '🌟', label: 'すべて' },
  { id: 'minimal', emoji: '✨', label: 'ミニマル・洗練' },
  { id: 'tech', emoji: '🚀', label: 'テック・先進的' },
  { id: 'casual', emoji: '😊', label: '親しみやすい' },
  { id: 'premium', emoji: '👑', label: 'プレミアム・高級' },
  { id: 'creative', emoji: '🎨', label: 'クリエイティブ' },
  { id: 'corporate', emoji: '💼', label: 'ビジネス・信頼' }
];

const previewContent = {
  'swiss': `<span class="p-number">01</span><div class="p-title">Design</div><div class="p-accent"></div><div class="p-text">Rational approach</div>`,
  'japanese': `<div class="p-title">余白の美</div><div class="p-line"></div><div class="p-text">静寂と調和</div>`,
  'nordic': `<div class="p-card"><div class="p-dot"></div><div class="p-title">Hygge</div><div class="p-text">Warm minimal</div></div>`,
  'mono': `<div class="p-layout"><div class="p-block"></div><div><div class="p-title">BLACK & WHITE</div><div class="p-text">Pure contrast</div></div></div>`,
  'editorial': `<div class="p-eyebrow">Feature</div><div class="p-title">The Art of Less</div><div class="p-line"></div>`,
  'architectural': `<div class="p-grid"></div><div class="p-content"><span class="p-number">01</span><div class="p-title">STRUCTURE</div><div class="p-text">Precision</div></div>`,
  'bauhaus': `<div class="p-circle"></div><div class="p-rect"></div><div class="p-title">BAUHAUS</div><div class="p-text">Form follows function</div>`,
  'scandi': `<div class="p-content"><div class="p-icon">🌿</div><div class="p-title">Light & Air</div><div class="p-text">Simple living</div></div>`,
  'zen': `<div class="p-circle"></div><div class="p-title">無</div>`,
  'tech-dark': `<div class="p-grid"></div><div class="p-content"><div class="p-badge">v2.0</div><div class="p-title">Tech Stack</div><div class="p-text">Next-gen</div></div>`,
  'neon': `<div class="p-glow"></div><div class="p-content"><div class="p-title">NEON</div><div class="p-text">// glow.js</div></div>`,
  'cyber': `<div class="p-lines"></div><div class="p-content"><div class="p-title">CYBER</div><div class="p-text">Future</div></div>`,
  'terminal': `<div class="p-header"><div class="p-dot red"></div><div class="p-dot yellow"></div><div class="p-dot green"></div></div><div class="p-line"><span class="p-prompt">$</span> <span class="p-cmd">npm run</span></div><div class="p-line">✓ Done</div>`,
  'matrix': `<div class="p-rain">01010<br>10101<br>01010</div><div class="p-content"><div class="p-title">MATRIX</div><div class="p-text">Wake up...</div></div>`,
  'holographic': `<div class="p-shimmer"></div><div class="p-content"><div class="p-title">Hologram</div><div class="p-text">Iridescent</div></div>`,
  'ai': `<div class="p-nodes"><div class="p-node"></div><div class="p-node"></div><div class="p-node"></div><div class="p-node"></div></div><div class="p-content"><div class="p-title">Neural</div><div class="p-text">AI Network</div></div>`,
  'darkpro': `<div class="p-accent"></div><div class="p-title">Pro Dark</div><div class="p-text">Refined</div>`,
  'playful': `<div class="p-shapes"><div class="p-circle"></div><div class="p-square"></div></div><div class="p-content"><div class="p-emoji">🎉</div><div class="p-title">Play!</div><div class="p-text">Fun</div></div>`,
  'soft': `<div class="p-card"><div class="p-icon">✨</div><div class="p-title">Soft</div><div class="p-text">Gentle</div></div>`,
  'fresh': `<div class="p-blob"></div><div class="p-content"><div class="p-tag">NEW</div><div class="p-title">Fresh</div><div class="p-text">Clean</div></div>`,
  'rounded': `<div class="p-card"><div class="p-avatar"></div><div class="p-title">Hello!</div><div class="p-text">Friendly</div></div>`,
  'kawaii': `<div class="p-card"><div class="p-emoji">🎀</div><div class="p-title">Kawaii!</div></div>`,
  'organic': `<div class="p-shape"></div><div class="p-content"><div class="p-title">Organic</div><div class="p-text">Natural</div></div>`,
  'friendly': `<div class="p-card"><div class="p-icon">👋</div><div class="p-title">Hi there!</div></div>`,
  'memphis': `<div class="p-shapes"><div class="p-dot1"></div><div class="p-tri"></div><div class="p-line"></div></div><div class="p-content"><div class="p-title">MEMPHIS</div><div class="p-text">80s Pop</div></div>`,
  'luxury': `<div class="p-border"></div><div class="p-content"><div class="p-logo">LUXURY</div><div class="p-title">Elegance</div><div class="p-line"></div></div>`,
  'brutalist': `<div class="p-title">BOLD</div><div class="p-text">// raw.min</div>`,
  'artdeco': `<div class="p-frame"></div><div class="p-corner tl"></div><div class="p-corner br"></div><div class="p-content"><div class="p-title">DECO</div></div>`,
  'marble': `<div class="p-content"><div class="p-title">Marble</div><div class="p-line"></div></div>`,
  'noir': `<div class="p-vignette"></div><div class="p-content"><div class="p-title">Noir</div><div class="p-text">Shadow</div></div>`,
  'serif': `<div class="p-content"><div class="p-title">Serif</div><div class="p-text">Classic elegance</div></div>`,
  'museum': `<div class="p-label">EXHIBITION</div><div class="p-title">Artwork</div><div class="p-meta">2024, Digital</div>`,
  'fashion': `<div class="p-content"><div class="p-title">VOGUE</div><div class="p-line"></div></div>`,
  'geometric': `<div class="p-shapes"><div class="p-circle"></div><div class="p-square"></div></div><div class="p-title">Shapes</div><div class="p-text">Structure</div>`,
  'retro': `<div class="p-badge">VINTAGE</div><div class="p-title">Retro</div><div class="p-text">Classic</div>`,
  'gradient': `<div class="p-content"><div class="p-title">VIBRANT</div><div class="p-text">Bold</div></div>`,
  'duotone': `<div class="p-image"></div><div class="p-title">Duo</div><div class="p-text">Two-tone</div>`,
  'popart': `<div class="p-dots"></div><div class="p-content"><div class="p-title">POP!</div><div class="p-text">Art</div></div>`,
  'collage': `<div class="p-layer1"></div><div class="p-layer2"></div><div class="p-content"><div class="p-title">Collage</div></div>`,
  'grunge': `<div class="p-noise"></div><div class="p-content"><div class="p-title">GRUNGE</div></div>`,
  'experimental': `<div class="p-glitch">EXP</div><div class="p-content"><div class="p-title">Glitch</div><div class="p-text">Broken</div></div>`,
  'corporate': `<div class="p-header"><div class="p-logo"></div><div class="p-brand">CORP</div></div><div class="p-title">Business</div><div class="p-text">Trust</div>`,
  'data': `<div class="p-chart"><div class="p-bar" style="height:25px"></div><div class="p-bar" style="height:40px"></div><div class="p-bar" style="height:35px"></div><div class="p-bar" style="height:50px"></div></div><div class="p-title">Analytics</div><div class="p-text">Data</div>`,
  'consulting': `<div class="p-accent"></div><div class="p-title">Strategy</div><div class="p-text">Insight</div>`,
  'finance': `<div class="p-number">+24.5%</div><div class="p-label">Growth</div>`,
  'healthcare': `<div class="p-icon">💚</div><div class="p-title">Health</div><div class="p-text">Care</div>`,
  'legal': `<div class="p-scales">⚖️</div><div class="p-title">Justice</div><div class="p-text">Trust</div>`
};

// 目的別設定
const purposes = [
  { id: 'presentation', label: 'プレゼン', icon: '📊' },
  { id: 'website', label: 'Webサイト', icon: '🌐' },
  { id: 'app', label: 'アプリ', icon: '📱' },
  { id: 'lp', label: 'LP', icon: '🎯' },
  { id: 'social', label: 'SNS', icon: '📸' }
];
